INSERT INTO public.puzzle (id, answer, category, instruction, level, puzzle_item, rating, submission_time, title, member_id) VALUES (2, 'sakkozik', 'RIDDLE', 'Válaszolj egy szóval!', 0, 'Öt nővér van a szobában: Anna könyvet olvas, Marcsi főz, Kati sakkozik, Laura vasal. Mit csinál az ötödik testvér?', 0, '2019-09-10 00:00:15.853261', 'Nővérek', 1);
INSERT INTO public.puzzle (id, answer, category, instruction, level, puzzle_item, rating, submission_time, title, member_id) VALUES (3, '10', 'MATH_PUZZLE', 'Válaszolj egy számmal!', 0, 'Egy béka beleesett egy 12 méter mély kútba. Fel tudott ugrani 3 métert, de mindegyik ugrásnál vissza is esett 2 métert. Hányat kellett ugrania, hogy kijusson a kútból?', 0, '2019-09-10 00:01:24.854232', 'Béka', 1);
INSERT INTO public.puzzle (id, answer, category, instruction, level, puzzle_item, rating, submission_time, title, member_id) VALUES (4, '3.5, 4.5, 9.5, 3.5', 'PICTURE_PUZZLE', 'Milyen számok kerülnek a négyzetekbe? A megoldást ebben a sorrendben add meg: bal felső szám, jobb felső szám, bal alsó szám, jobb alsó szám - vesszővel és szóközzel elválasztva. Ha szükséges, használj tizedespontot! Pl.: 1, 2.5, 3, 4', 1, 'math-3.5.jpeg', 0, '2019-09-10 00:09:35.938604', 'Alapműveletek', 1);
INSERT INTO public.puzzle (id, answer, category, instruction, level, puzzle_item, rating, submission_time, title, member_id) VALUES (5, 'koporsó', 'RIDDLE', 'Válaszolj egy szóval!', 0, 'Aki készíti, annak nem kell. Aki megveszi, az nem használja. Aki használja, nem tud róla. Mi az?', 0, '2019-09-10 00:10:57.700667', 'Használati tárgy (?)', 1);
INSERT INTO public.puzzle (id, answer, category, instruction, level, puzzle_item, rating, submission_time, title, member_id) VALUES (6, '4', 'MATH_PUZZLE', 'Válaszolj egy számmal!', 0, 'A fiókban van 14 barna zokni, 14 kék zokni és 14 fekete zokni. Hány zoknit kell kivenned (csukott szemmel), hogy biztosan legyen köztük két azonos színű?', 0, '2019-09-10 00:12:33.845311', 'Zoknik', 1);
INSERT INTO public.puzzle (id, answer, category, instruction, level, puzzle_item, rating, submission_time, title, member_id) VALUES (7, '40', 'PICTURE_PUZZLE', 'Hány négyzet van a képen? Válaszolj egy számmal!', 1, 'squares40.png', 0, '2019-09-10 00:13:39.417713', 'Négyzetek', 1);
INSERT INTO public.puzzle (id, answer, category, instruction, level, puzzle_item, rating, submission_time, title, member_id) VALUES (8, 'semmi', 'RIDDLE', 'Válaszolj egy szóval!', 0, 'Nagyobb Istennél, gonoszabb az ördögnél, a szegénynek van, a gazdagnak szüksége van rá, és aki ezt eszi, meghal - mi az?', 0, '2019-09-10 00:17:31.821912', 'Létkérdés', 1);
INSERT INTO public.puzzle (id, answer, category, instruction, level, puzzle_item, rating, submission_time, title, member_id) VALUES (9, 'tegnap, ma, holnap', 'RIDDLE', 'Válaszolj három szóval, vesszővel és szóközzel válaszd el őket!', 0, 'Meg tudsz nevezni három egymást követő napot anélkül, hogy használnád a hétfő, kedd, szerda, csütörtök, péntek, szombat és vasárnap szavakat?', 0, '2019-09-10 00:20:09.001157', 'Napok', 1);
INSERT INTO public.puzzle (id, answer, category, instruction, level, puzzle_item, rating, submission_time, title, member_id) VALUES (10, '4, 3', 'MATH_PUZZLE', 'Válaszolj két számmal: méhek száma, virágok száma (pl. 1, 2)!', 0, 'Egy ágyásban van néhány virág, és néhány méhecske ül rajtuk. Hányan vannak a méhecskék és a virágok, ha igaz mindkét állítás:
1. ha minden virágra egy méh száll, egy méhecskének nem jut virág,
2. ha két méh osztozik egy virágon, egy virág üresen marad?', 0, '2019-09-10 00:25:54.172621', 'Virágok és méhecskék', 1);
INSERT INTO public.puzzle (id, answer, category, instruction, level, puzzle_item, rating, submission_time, title, member_id) VALUES (11, '40, 12', 'MATH_PUZZLE', 'Válaszolj két számmal: Bill életkora, a fia életkora (pl. 20, 2)!', 0, '8 évvel ezelőtt Bill 8-szor annyi idős volt, mint a kisfia. Ma, ha összeadjuk a korukat, 52-t kapunk. Hány éves Bill és a fia?', 0, '2019-09-10 00:29:49.782851', 'Korkérdés', 1);
INSERT INTO public.puzzle (id, answer, category, instruction, level, puzzle_item, rating, submission_time, title, member_id) VALUES (12, '1185', 'MATH_PUZZLE', 'Válaszolj egy számmal!', 0, 'Melyik az a négyjegyű szám, amiben az első számjegy egy-ötöde az utolsónak, a két középső számjegy együttesen pedig a szélső számjegyek összege 3-mal szorozva?', 0, '2019-09-10 00:34:41.566664', 'Számjegyek', 1);
INSERT INTO public.puzzle (id, answer, category, instruction, level, puzzle_item, rating, submission_time, title, member_id) VALUES (13, '3', 'PICTURE_PUZZLE', 'Melyik a piramis felülnézetből? Válaszolj egy számmal!', 0, 'piramis.jpg', 0, '2019-09-10 00:44:40.030168', 'Piramis', 1);
INSERT INTO public.puzzle (id, answer, category, instruction, level, puzzle_item, rating, submission_time, title, member_id) VALUES (14, '10', 'PICTURE_PUZZLE', 'Hány számot látsz a képen?', 1, 'numbers.jpg', 0, '2019-09-10 00:45:19.063820', 'Számok', 1);
INSERT INTO public.puzzle (id, answer, category, instruction, level, puzzle_item, rating, submission_time, title, member_id) VALUES (15, '81', 'PICTURE_PUZZLE', 'Válaszolj egy számmal!', 0, 'flowers.jpg', 0, '2019-09-10 00:48:05.152872', 'Virágok', 1);
INSERT INTO public.puzzle (id, answer, category, instruction, level, puzzle_item, rating, submission_time, title, member_id) VALUES (16, '100', 'RIDDLE', 'Válaszolj egy számmal! Melyik a számsor következő eleme?', 1, '1, 4, 5, 6, 7, 8, 10, 20, ?', 0, '2019-09-10 00:56:08.413912', 'Trükkös számsor', 1);
INSERT INTO public.puzzle (id, answer, category, instruction, level, puzzle_item, rating, submission_time, title, member_id) VALUES (17, 'Száz sasszem meg száz sasszem az sok száz sasszem.', 'CIPHER', 'Fejtsd meg a titkosírást! Az abc minden betűjét "arréb toltuk" valamennyivel.', 0, 'űdéd űeűűdiő őik űdéd űeűűdiő ed űqó űdéd űeűűdiő.', 0, '2019-09-10 00:57:15.955887', 'Nyelvtörő', 1);
INSERT INTO public.puzzle (id, answer, category, instruction, level, puzzle_item, rating, submission_time, title, member_id) VALUES (18, 'Ki mint veti ágyát, úgy alussza álmát.', 'CIPHER', 'Fejtsd meg a titkosírást! Az abc minden betűje egy másik betűnek felel meg, teljesen véletlenszerűen. Egy kis segítség: {á=á, t=é, i=k}. Az egyenlőségjel bal oldalán az eredeti betű áll, a jobb oldalon a titkosírásban használt megfelelője.', 2, 'ik xkhé poék áűfáé, nűf tgraaet ágxáé.', 0, '2019-09-10 00:59:09.564490', 'Közmondás', 1);
INSERT INTO public.puzzle (id, answer, category, instruction, level, puzzle_item, rating, submission_time, title, member_id) VALUES (19, 'Szegény az eklézsia, maga harangoz a pap.', 'CIPHER', 'Fejtsd meg a titkosírást! Az abc minden betűje egy másik betűnek felel meg, teljesen véletlenszerűen. Egy kis segítség: {a=h, g=ű, z=n}. Az egyenlőségjel bal oldalán az eredeti betű áll, a jobb oldalon a titkosírásban használt megfelelője.', 2, 'mnöűúfe hn ösüúnmvh, rhűh jhíhfűln h őhő.', 0, '2019-09-10 01:01:26.801468', 'Egyház', 1);
INSERT INTO public.puzzle (id, answer, category, instruction, level, puzzle_item, rating, submission_time, title, member_id) VALUES (20, 'Segíts magadon, az Isten is megsegít.', 'CIPHER', 'Fejtsd meg a titkosírást! Az abc minden betűje egy másik betűnek felel meg, teljesen véletlenszerűen. Egy kis segítség: {a=r, s=g, t=í, e=n, g=j}. Az egyenlőségjel bal oldalán az eredeti betű áll, a jobb oldalon a titkosírásban használt megfelelője.', 1, 'gnjáíg qrjrzbc, rú hgínc hg qnjgnjáí.', 0, '2019-09-10 01:03:39.862334', 'Jó tanács', 1);
INSERT INTO public.puzzle (id, answer, category, instruction, level, puzzle_item, rating, submission_time, title, member_id) VALUES (21, 'A kecske is jóllakik és a káposzta is megmarad.', 'CIPHER', 'Fejtsd meg a titkosírást! Az abc minden betűjét "arréb toltuk" valamennyivel.', 0, 'e óigűói mű orööeómó íű e óéuqűdve mű őikőeüeh.', 0, '2019-09-10 01:10:16.560062', 'Nyertesek', 1);
INSERT INTO public.puzzle (id, answer, category, instruction, level, puzzle_item, rating, submission_time, title, member_id) VALUES (22, 'Makó', 'WORD_PUZZLE', 'Milyen szótag egészíti ki mindkét szót a szórejtvény első felében? És a másodikban? Melyik város nevét kapjuk a két szótagból?', 1, '1. pál-_____-lom
2. tar-_____-rus', 0, '2019-09-10 01:20:58.825176', 'Városnév', 1);
INSERT INTO public.puzzle (id, answer, category, instruction, level, puzzle_item, rating, submission_time, title, member_id) VALUES (23, 'ál, ékszer, fa, tánc, vándor', 'WORD_PUZZLE', 'Keresd meg a rejtvény mindegyik részéhez azt az előtagot, ami értelmes szóösszetételt képez a megadott utótagokkal! A válasz az öt szó ábécé sorrendben, vesszővel, szóközzel elválasztva.', 2, '1. ______ -gyöngy, -ipar, -ló
2. ______ -doboz, -teknős, -üzlet
3. ______ -szent, -ruha, -szakáll
4. ______ -tanár, -cipő, -ház
5. ______ -bot, -út, -díj', 0, '2019-09-10 01:27:23.505308', 'Szóösszetételek', 1);
INSERT INTO public.puzzle (id, answer, category, instruction, level, puzzle_item, rating, submission_time, title, member_id) VALUES (24, 'csalétek', 'WORD_PUZZLE', 'A rejtvény mindhárom sorában a megadott két szót egy szótag vagy egy betű egészíti ki. A három részmegoldásból egy új szó jön ki. Melyik ez a szó?', 1, '1. kan- _____ -fa
2. szak- _____ -szak
3. pén- _____ -nős', 0, '2019-09-10 01:32:11.644387', 'Horogra akadt?', 1);
INSERT INTO public.puzzle (id, answer, category, instruction, level, puzzle_item, rating, submission_time, title, member_id) VALUES (25, 'emu', 'WORD_PUZZLE', 'Melyik állatnév a kakukktojás?', 0, 'sas, uhu, emu, ürü, acsa', 0, '2019-09-10 01:45:09.509203', 'Kakukktojás', 1);